/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_wz_androidjnitest_ndk_NdkTest */

#ifndef _Included_com_wz_androidjnitest_ndk_NdkTest
#define _Included_com_wz_androidjnitest_ndk_NdkTest
#ifdef __cplusplus
extern "C" {
#endif
/*
 * Class:     com_wz_androidjnitest_ndk_NdkTest
 * Method:    ndkSayHello
 * Signature: ()Ljava/lang/String;
 */
JNIEXPORT jstring JNICALL Java_com_wz_androidjnitest_ndk_NdkTest_ndkSayHello
  (JNIEnv *, jobject);

#ifdef __cplusplus
}
#endif
#endif
